-- Enable UUID extension (optional but good practice)
create extension if not exists "uuid-ossp";

-- 1. Public Health Alerts Table
create table if not exists public_health_alerts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  date text, -- Using text for flexible date formats as per model
  tag text,
  source text,
  country text default 'INDIA'
);

-- Seed Data for Alerts (With recent dates)
insert into public_health_alerts (title, description, date, tag, source, country) values
('Urgent: Water Contamination Alert in New Delhi', 'High levels of coliform bacteria detected in municipal supply in West Delhi. Boil water advisory issued.', '2/14/2026', 'Contamination', 'Delhi Jal Board', 'INDIA'),
('Cholera Outbreak Contained in Odisha', 'Rapid response teams have successfully contained the minor outbreak in coastal districts.', '2/13/2026', 'Cholera', 'State Health Dept', 'INDIA'),
('New Water Purification Plant Inaugurated', 'A state-of-the-art purification plant opens in Chennai to serve 50,000 households.', '2/12/2026', 'Infrastructure', 'The Hindu', 'INDIA'),
('Dengue Watch: Mosquite Breeding Sites Identified', 'Municipal corporation identifies and treats over 500 breeding sites near stagnant water bodies.', '2/11/2026', 'Dengue', 'Times of India', 'INDIA'),
('Rise in Typhoid Cases in Urban Slums', 'NGOs report a 15% increase in typhoid cases due to lack of clean drinking water.', '2/10/2026', 'Typhoid', 'Health Beat', 'INDIA');

-- 2. State Disease Data Table
create table if not exists state_disease_data (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  state_name text not null,
  cases bigint,
  rate_per_1000 numeric
);

-- Seed Data for State Data
insert into state_disease_data (state_name, cases, rate_per_1000) values
('Uttar Pradesh', 95000, 0.52),
('West Bengal', 88000, 0.45),
('Maharashtra', 78000, 0.35),
('Bihar', 65000, 0.61),
('Gujarat', 52000, 0.22),
('Punjab', 45000, 0.15),
('Kerala', 32000, 0.09),
('Tamil Nadu', 41000, 0.18);

-- 3. Disease Trends Table
create table if not exists disease_trends (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  month text not null,
  cholera_cases bigint,
  diarrhea_cases bigint,
  typhoid_cases bigint
);

-- Seed Data for Trends
insert into disease_trends (month, cholera_cases, diarrhea_cases, typhoid_cases) values
('Jan', 8200, 11500, 6100),
('Feb', 8900, 13200, 6800),
('Mar', 10500, 16000, 8500),
('Apr', 11200, 18500, 9200),
('May', 13500, 22000, 11000);
